spring.application.name=job-portal-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-146e4392-r0hiitverma1095-5d94.a.aivencloud.com:15919/defaultdb?sslMode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_0XcXdbXsaDTtxhxXlPU}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

brevo.api.key=${BREVO_API_KEY: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}

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:djmtdgsfg}
cloudinary.api-key=${CLOUDINARY_API_KEY:783139348564715}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:qlEzwqTLKOWwToqzt_GKy5NtHQY}